<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="TCOEW42SLPC6899" failures="1" tests="1" name="Default test(failed)" time="0.037" errors="0" timestamp="2022-06-06T10:21:28 IST">
  <testcase classname="TestngReRunFailed.ReRunTest" name="test4" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
at TestngReRunFailed.ReRunTest.test4(ReRunTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="TestngReRunFailed.ReRunTest" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="TestngReRunFailed.ReRunTest" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="TestngReRunFailed.ReRunTest" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
